### ISSUE TITLE
runtime deep call stacks

### ISSUE THREAD

**Issue by hallas** [roncohen/opbeat-go#10]
@roncohen 

So I've been tracking and experimenting a bit with some errors and found that the stacks get pretty deep when something like trying to access a nil pointer reference happens this means that the frame of the users code is shown somewhere in the middle of the stack in the Opbeat UI. Is there anyway we can look at the Opbeat API to be able to set a "most significant frame" or something like that?

**Comment by roncohen** [comment]
Hey!

Good point. The solution would be to use the undocumented `in_app` field to denote whether a frame should be considered user code or library code.  In the web interface, Opbeat will initially hide all non-all/library frames. 

There's hint of the `in_app` field here: https://github.com/roncohen/opbeat-go/blob/master/opbeat.go#L427. It's a boolean. 

I suggest being able to supply a white list of modules/packages that should be considered to be "user" code. Not sure what a sensible default would be.

What do you think?

**Comment by hallas** [comment]
Will think on it and try some more. Because when I think about it the in_app stuff should already be working. Maybe we should add some unit tests on the actual packets constructed by the library.
