### ISSUE TITLE
Investigate if getting the error type using reflection will improve grouping

### ISSUE THREAD

**Issue by roncohen** [roncohen/opbeat-go#12]

**Comment by hallas** [comment]
Grouping of the stack frames?

**Comment by roncohen** [comment]
Grouping of the errors - on Opbeat.com

**Comment by roncohen** [comment]
https://opbeat.com/docs/api/intake/v1/#exception

**Comment by hallas** [comment]
Ah. Makes sense :-)

**Comment by hallas** [comment]
Not a lot of type in errors as they are now but potentially you could use reflect to support any value that implements the error interface as seen here:

http://golang.org/src/builtin/builtin.go?s=10777:10817#L244
http://golang.org/src/errors/errors.go
