### ISSUE TITLE
error when trying before trying to queue packet from client with no credentials

### ISSUE THREAD

**Issue by hallas** [roncohen/opbeat-go#9]
@roncohen 

I want to add a check in `CaptureMessage` and `CaptureErrorSkip` thats stops us from enqueuing packets on a client that has no credentials anyway. (happens when you use the default client without environment variables).

What do you think?

**Comment by roncohen** [comment]
Yeah, that makes a lot of sense.

**Comment by roncohen** [comment]
Fixed by https://github.com/roncohen/opbeat-go/pull/15
